CREATE DATABASE if not exists store;
--
USE store;
--
CREATE TABLE IF NOT EXISTS users(
iduser int auto_increment primary key,
name VARCHAR(50) NOT NULL,
lastname VARCHAR(50) NOT NULL,
username VARCHAR(50) NOT NULL UNIQUE,
email VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
birthday DATE NOT NULL,
balance DOUBLE DEFAULT 0,
status ENUM('ACTIVE','DELETED') DEFAULT 'ACTIVE',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
--
CREATE TABLE IF NOT EXISTS roles(
idrole VARCHAR(50) primary key,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
--
CREATE TABLE IF NOT EXISTS users_has_roles(
iduser int,
idrole VARCHAR(50),
PRIMARY KEY (iduser,idrole),
FOREIGN KEY (iduser) REFERENCES users(iduser),
FOREIGN KEY (idrole) REFERENCES roles(idrole)
);
--
CREATE TABLE IF NOT EXISTS products(
idproduct INT auto_increment primary key,
code VARCHAR(50) UNIQUE NOT NULL,
price DOUBLE NOT NULL,
material VARCHAR(50) NOT NULL,
type_product VARCHAR(50) NOT NULL,
register_day DATE NOT NULL,
size VARCHAR(50) NOT NULL,
brand VARCHAR(50) NOT NULL,
waterproof BOOLEAN NOT NULL,
weight INT NOT NULL,
gadget VARCHAR(50) NOT NULL,
security VARCHAR(50),
wheels BOOLEAN NOT NULL,
status ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
--
CREATE TABLE IF NOT EXISTS address(
idaddress INT auto_increment PRIMARY KEY,
iduser INT NOT NULL,
street VARCHAR(50)  NOT NULL,
country VARCHAR(50)  NOT NULL,
city VARCHAR(50)  NOT NULL,
apartarment VARCHAR(50)  NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
--
CREATE TABLE IF NOT EXISTS orders(
idorder INT AUTO_INCREMENT PRIMARY KEY,
iduser INT NOT NULL,
idproduct INT NOT NULL,
price DOUBLE NOT NULL,
status ENUM('PAID', 'REFUND') NOT NULL DEFAULT 'PAID',
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
--
ALTER TABLE address
ADD FOREIGN KEY (iduser) REFERENCES users(iduser);
--
ALTER TABLE orders
ADD FOREIGN KEY (iduser) REFERENCES users(iduser),
ADD FOREIGN KEY (idproduct) REFERENCES products(idproduct);
--
INSERT INTO roles(idrole) VALUES ('ADMIN');
--
INSERT INTO roles(idrole) VALUES ('CLIENT');
--
create procedure insertAdmin(
     p_name VARCHAR(50),
     p_lastname VARCHAR(50),
     p_username VARCHAR(50),
     p_email VARCHAR(50),
     p_password VARCHAR(64),
     p_birthday DATE
)
begin
 DECLARE total INT;

 SELECT COUNT(*) INTO total FROM users;

 if(total = 0)
 THEN
        INSERT INTO users(name, lastname, username, email, password, birthday)
        VALUES (p_name, p_lastname, p_username, p_email, p_password, p_birthday);
    END IF;
END;
--
create procedure accessAdmin()
begin
 DECLARE total INT;
 DECLARE f_iduser INT;
 DECLARE f_idrole VARCHAR(50);

 SELECT COUNT(*) INTO total FROM users_has_roles;

 if(total = 0)
 THEN
    SELECT iduser INTO f_iduser FROM users WHERE username = 'admin' LIMIT 1;
    SELECT idrole INTO f_idrole FROM roles WHERE idrole = 'ADMIN';

          INSERT INTO users_has_roles(iduser,idrole)
        VALUES (f_iduser,f_idrole);
    END IF;
END;
--
INSERT INTO products
(code, price, material, type_product, register_day, size, brand, waterproof, weight, gadget, security, wheels)
VALUES
('PROD001', 120.50, 'LEATHER', 'BAG', CURRENT_DATE, 'M', 'SAMSONITE', TRUE, 1.2, 'WALLET', 'NONE', FALSE),
('PROD002', 89.99, 'FABRIC', 'BAG', CURRENT_DATE, 'L', 'EASTPAK', TRUE, 0.8, 'BACKPACK', 'NONE', FALSE),
('PROD003', 150.00, 'CANVAS', 'TRAVELBAG', CURRENT_DATE, 'M', 'ADIDAS', FALSE, 1.5, 'SHOULDERBAG', 'NONE', FALSE),
('PROD004', 200.00, 'LEATHER', 'SUITCASE', CURRENT_DATE, 'L', 'NIKE', TRUE, 2.5, 'NONE', 'LOCK', FALSE),
('PROD005', 75.50, 'NYLON', 'BAG', CURRENT_DATE, 'S', 'HERSCHEL', FALSE, 0.7, 'HANDSFREE', 'NONE', FALSE),
('PROD006', 99.99, 'POLYESTER', 'BAG', CURRENT_DATE, 'M', 'GENERICA', TRUE, 1.0, 'BACKPACK', 'NONE', FALSE),
('PROD007', 130.00, 'LEATHER', 'TRAVELBAG', CURRENT_DATE, 'L', 'SAMSONITE', TRUE, 1.8, 'SHOULDERBAG', 'NONE',FALSE),
('PROD008', 60.00, 'FABRIC', 'BAG', CURRENT_DATE, 'S', 'EASTPAK', FALSE, 0.6, 'WALLET', 'NONE', FALSE),
('PROD009', 180.00, 'NYLON', 'SUITCASE', CURRENT_DATE, 'L', 'ADIDAS', TRUE, 2.0, 'NONE', 'LOCK', TRUE),
('PROD010', 110.00, 'CANVAS', 'TRAVELBAG', CURRENT_DATE, 'M', 'NIKE', FALSE, 1.4, 'SHOULDERBAG', 'NONE', FALSE),
('PROD011', 95.50, 'LEATHER', 'BAG', CURRENT_DATE, 'M', 'HERSCHEL', TRUE, 1.1, 'HANDSFREE', 'NONE', FALSE),
('PROD012', 70.00, 'POLYESTER', 'BAG', CURRENT_DATE, 'S', 'GENERICA', FALSE, 0.9, 'BACKPACK', 'NONE', FALSE),
('PROD013', 145.00, 'CANVAS', 'TRAVELBAG', CURRENT_DATE, 'L', 'SAMSONITE', TRUE, 1.6, 'SHOULDERBAG', 'NONE', FALSE),
('PROD014', 85.00, 'FABRIC', 'BAG', CURRENT_DATE, 'S', 'EASTPAK', FALSE, 0.7, 'WALLET', 'NONE', FALSE),
('PROD015', 175.00, 'NYLON', 'SUITCASE', CURRENT_DATE, 'L', 'ADIDAS', TRUE, 2.3, 'NONE', 'LOCK', FALSE),
('PROD016', 115.00, 'LEATHER', 'TRAVELBAG', CURRENT_DATE, 'M', 'NIKE', FALSE, 1.5, 'SHOULDERBAG', 'NONE', FALSE),
('PROD017', 90.00, 'POLYESTER', 'BAG', CURRENT_DATE, 'S', 'HERSCHEL', TRUE, 0.8, 'HANDSFREE', 'NONE', FALSE),
('PROD018', 105.00, 'CANVAS', 'BAG', CURRENT_DATE, 'M', 'GENERICA', TRUE, 1.3, 'BACKPACK', 'NONE', FALSE),
('PROD019', 160.00, 'LEATHER', 'TRAVELBAG', CURRENT_DATE, 'L', 'SAMSONITE', TRUE, 1.9, 'SHOULDERBAG', 'NONE', FALSE),
('PROD020', 80.00, 'FABRIC', 'BAG', CURRENT_DATE, 'S', 'EASTPAK', FALSE, 0.6, 'WALLET', 'NONE', FALSE);




